### ISSUE TITLE
Direct stable URL to canary.tgz?

### ISSUE THREAD

**Issue by ef4** [ember-cli/ember-source-channel-url#205]
Is there a reason that, whenever the `canary.json` gets written to S3, we can't simultaneously write a file like `canary.tgz` containing the build? Then you wouldn't need to run ember-source-channel-url to discover the tarball, you could point directly to the tarball from your package.json.

**Comment by rwjblue** [comment]
@ef4 - Yes, we tried that, but `yarn` caches based on the tarball URL and you end up getting mega-trolled (because one person has "canary" that means one SHA and another has "canary" that means a totally different one).

**Comment by rwjblue** [comment]
@ef4 - One thing to note here though, is that I am planning to setup auto-publishing of weekly `-alpha` releases to `npm` (hopefully this week) so this package will be much less needed. (Not sure that helps / hurts your end goal here, but figured I'd mention it JIC).

**Comment by ef4** [comment]
Thanks!
