### ISSUE TITLE
channels for ember-data

### ISSUE THREAD

**Issue by xcambar** [ember-cli/ember-source-channel-url#5]
Hi,
Considering the name of the repo, is it the right place to ask for the possibility of returning the URLs for the ember-data channels too?
That would certainly be lovely. At least for consistency's sake.

**Comment by rwjblue** [comment]
I'm not sure how it would work since ember-data can be used directly from github...

**Comment by xcambar** [comment]
I thought ember-data would be/was published to S3 as Ember itself, and we would be allowed to extend the API of this addon just enough as to generate the ember-data URLs as well.

Being able to use ember-data from GH is fine (and more than enough) but my ember-try config (using a mix of ember and ember-data) fells a bit inconsistent with a bit of this plugin on one hand and a bit of GH references on the other :) 

As you can see, no big worries here :p

**Comment by fsmanuel** [comment]
@xcambar Out of curiosity how does your `ember-try` config look like?
I'm facing this for https://github.com/funkensturm/ember-local-storage/pull/301

**Comment by xcambar** [comment]
Here's the relevant parts. Let me know if you have questions.

```
[
  {
    name: 'ember-lts-2.18',
    npm: {
      devDependencies: {
        'ember-data': 'emberjs/data#2.18.4',
        'ember-source': '~2.18.0'
      }
    }
  },
  {
    name: 'ember-release',
    npm: {
      devDependencies: {
        'ember-data': 'emberjs/data#release',
        'ember-source': urls[0]
      }
    }
  },
  {
    name: 'ember-beta',
    npm: {
      devDependencies: {
        'ember-data': 'emberjs/data#beta',
        'ember-source': urls[1]
      }
    }
  },
  {
    name: 'ember-canary',
    npm: {
      devDependencies: {
        'ember-data': 'emberjs/data#master',
        'ember-source': urls[2]
      }
    }
  },
  {
    name: 'ember-default',
    npm: {
      devDependencies: {}
    }
  }
]
```

The `urls` variable contains the URLS for `ember-source`, as per the default blueprint.

**Comment by fsmanuel** [comment]
@xcambar Thanks a lot!
