### ISSUE TITLE
Amazon S3 will no longer support path-style API requests starting September 30th, 2020 

### ISSUE THREAD

**Issue by locks** [ember-cli/ember-source-channel-url#59]
In short, it seems `//s3.amazonaws.com/<bucketname>/key` will no longer be supported to be replaced with `//<bucketname>.s3.amazonaws.com/key`.

More info: https://forums.aws.amazon.com/ann.jspa?annID=6776

**Comment by rwjblue** [comment]
I think this means that we will loose the ability to use HTTPS for these requests (without additional hoop jumping that is). We may need to change the bucket name to avoid including a period...

**Comment by rwjblue** [comment]
Amazon updated there policy, the link above now states:

> On April 30, 2019, we posted a deprecation announcement of path-style requests (see below). In response to feedback on the original deprecation plan, we are making an important change. Here is a summary, and please view this Jeff Barr Blog for more details:
> 
> Original Plan: Support for the path-style model ends on September 30, 2020 (see below).
> 
> Revised Plan: S3 buckets created after September 30, 2020 will support only virtual-hosted style requests. Path-style requests will continue to be supported for buckets created on or before this date.
